/*
  ConstructionDWH - Kimball-guided PostgreSQL DDL v2

  Design highlights aligned with Kimball principles:
  - Star schema with conformed dimensions
  - Explicit grain for each fact table
  - Surrogate keys in dimensions (GENERATED BY DEFAULT AS IDENTITY)
  - Type 2 Slowly Changing Dimensions (SCD2) for core entities
  - Unknown member rows (-1) in each dimension
  - Degenerate dimensions in facts (DocumentNumber, LineNumber)
  - BRIN indexes on DateKey for efficient scans on large, date-ordered fact tables

  Notes for large-volume efficiency (Requirement: "handle large volumes of data efficiently"):
  - Consider RANGE partitioning the fact tables by DateKey once volumes justify it
    (PARTITION BY RANGE (DateKey), with per-year/month partitions). Not applied here
    to keep the initial schema simple; the loader can insert into the parent table
    unchanged if partitioning is added later.
  - Consider running ANALYZE/VACUUM maintenance and, for read-heavy analytics,
    evaluate columnar extensions (e.g. Citus/columnar, hydra) if native Postgres
    heap storage becomes a bottleneck.
  - For ML/prediction workloads (Requirement 2), consider optional extensions such as
    plpython3u or pgvector depending on the modeling approach; none are required by
    this schema.
*/

BEGIN;

CREATE SCHEMA IF NOT EXISTS dwh;

/* =========================
   DROP OBJECTS (RE-RUN SAFE)
   ========================= */

DROP TABLE IF EXISTS dwh.FactCommitted CASCADE;
DROP TABLE IF EXISTS dwh.FactActual CASCADE;
DROP TABLE IF EXISTS dwh.FactPlanned CASCADE;

DROP TABLE IF EXISTS dwh.DimWBS CASCADE;
DROP TABLE IF EXISTS dwh.DimProject CASCADE;
DROP TABLE IF EXISTS dwh.DimResource CASCADE;
DROP TABLE IF EXISTS dwh.DimCustomer CASCADE;
DROP TABLE IF EXISTS dwh.DimSupplier CASCADE;
DROP TABLE IF EXISTS dwh.DimProduct CASCADE;
DROP TABLE IF EXISTS dwh.DimDate CASCADE;
DROP TABLE IF EXISTS dwh.DimAudit CASCADE;

DROP PROCEDURE IF EXISTS dwh.usp_PopulateDimDate(DATE, DATE);

/* =========================
   DIMENSIONS (CONFORMED)
   ========================= */

CREATE TABLE dwh.DimDate (
    DateKey                 INTEGER NOT NULL PRIMARY KEY,
    FullDate                DATE NOT NULL,
    DayNumberOfMonth        SMALLINT NOT NULL,
    DayName                 VARCHAR(20) NOT NULL,
    DayOfWeekISO            SMALLINT NOT NULL,
    WeekOfYearISO           SMALLINT NOT NULL,
    MonthNumber             SMALLINT NOT NULL,
    MonthName               VARCHAR(20) NOT NULL,
    QuarterNumber           SMALLINT NOT NULL,
    YearNumber              SMALLINT NOT NULL,
    YearMonth               CHAR(7) NOT NULL,
    IsWeekend               BOOLEAN NOT NULL,
    IsMonthEnd              BOOLEAN NOT NULL,
    CONSTRAINT UQ_DimDate_FullDate UNIQUE (FullDate)
);

CREATE TABLE dwh.DimAudit (
    AuditKey                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BatchId                 VARCHAR(100) NOT NULL,
    SourceSystem            VARCHAR(100) NOT NULL,
    LoadStartDtm            TIMESTAMP(0) NOT NULL,
    LoadEndDtm              TIMESTAMP(0) NULL,
    LoadStatus              VARCHAR(30) NOT NULL,
    RowsRead                BIGINT NULL,
    RowsInserted            BIGINT NULL,
    RowsUpdated             BIGINT NULL,
    ErrorMessage            VARCHAR(2000) NULL
);

CREATE TABLE dwh.DimProject (
    ProjectKey              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProjectBK               VARCHAR(50) NOT NULL,
    ProjectName             VARCHAR(255) NOT NULL,
    ProjectType             VARCHAR(100) NULL,
    ProjectStatus           VARCHAR(50) NULL,
    PlannedStartDate        DATE NULL,
    PlannedEndDate          DATE NULL,
    SCDStartDate            DATE NOT NULL,
    SCDEndDate              DATE NOT NULL,
    IsCurrent               BOOLEAN NOT NULL,
    RecordSource            VARCHAR(100) NULL,
    CONSTRAINT CK_DimProject_SCDRange CHECK (SCDEndDate >= SCDStartDate)
);

CREATE TABLE dwh.DimWBS (
    WBSKey                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    WBSBK                   VARCHAR(80) NOT NULL,
    WBSName                 VARCHAR(255) NOT NULL,
    WBSType                 VARCHAR(50) NULL,
    ParentWBSBK             VARCHAR(80) NULL,
    WBSLevel                INTEGER NULL,
    SCDStartDate            DATE NOT NULL,
    SCDEndDate              DATE NOT NULL,
    IsCurrent               BOOLEAN NOT NULL,
    RecordSource            VARCHAR(100) NULL,
    CONSTRAINT CK_DimWBS_SCDRange CHECK (SCDEndDate >= SCDStartDate)
);

CREATE TABLE dwh.DimResource (
    ResourceKey             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ResourceBK              VARCHAR(50) NOT NULL,
    ResourceName            VARCHAR(255) NOT NULL,
    ResourceType            VARCHAR(50) NOT NULL,
    Department              VARCHAR(100) NULL,
    UnitOfMeasure           VARCHAR(30) NULL,
    HourlyRate              NUMERIC(18,2) NULL,
    SCDStartDate            DATE NOT NULL,
    SCDEndDate              DATE NOT NULL,
    IsCurrent               BOOLEAN NOT NULL,
    RecordSource            VARCHAR(100) NULL,
    CONSTRAINT CK_DimResource_SCDRange CHECK (SCDEndDate >= SCDStartDate)
);

CREATE TABLE dwh.DimCustomer (
    CustomerKey             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CustomerBK              VARCHAR(50) NOT NULL,
    CustomerName            VARCHAR(255) NOT NULL,
    CustomerSegment         VARCHAR(100) NULL,
    Country                 VARCHAR(100) NULL,
    Region                  VARCHAR(100) NULL,
    City                    VARCHAR(100) NULL,
    SCDStartDate            DATE NOT NULL,
    SCDEndDate              DATE NOT NULL,
    IsCurrent               BOOLEAN NOT NULL,
    RecordSource            VARCHAR(100) NULL,
    CONSTRAINT CK_DimCustomer_SCDRange CHECK (SCDEndDate >= SCDStartDate)
);

CREATE TABLE dwh.DimSupplier (
    SupplierKey             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    SupplierBK              VARCHAR(50) NOT NULL,
    SupplierName            VARCHAR(255) NOT NULL,
    SupplierCategory        VARCHAR(100) NULL,
    Country                 VARCHAR(100) NULL,
    Region                  VARCHAR(100) NULL,
    City                    VARCHAR(100) NULL,
    SCDStartDate            DATE NOT NULL,
    SCDEndDate              DATE NOT NULL,
    IsCurrent               BOOLEAN NOT NULL,
    RecordSource            VARCHAR(100) NULL,
    CONSTRAINT CK_DimSupplier_SCDRange CHECK (SCDEndDate >= SCDStartDate)
);

CREATE TABLE dwh.DimProduct (
    ProductKey              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ProductBK               VARCHAR(50) NOT NULL,
    ProductName             VARCHAR(255) NOT NULL,
    ProductCategory         VARCHAR(100) NULL,
    UnitOfMeasure           VARCHAR(30) NULL,
    StandardCost            NUMERIC(18,2) NULL,
    SCDStartDate            DATE NOT NULL,
    SCDEndDate              DATE NOT NULL,
    IsCurrent               BOOLEAN NOT NULL,
    RecordSource            VARCHAR(100) NULL,
    CONSTRAINT CK_DimProduct_SCDRange CHECK (SCDEndDate >= SCDStartDate)
);

/* Current-row uniqueness per business key (SCD2), implemented as partial unique indexes */
CREATE UNIQUE INDEX UX_DimProject_CurrentBK ON dwh.DimProject(ProjectBK) WHERE IsCurrent = TRUE;
CREATE UNIQUE INDEX UX_DimWBS_CurrentBK ON dwh.DimWBS(WBSBK) WHERE IsCurrent = TRUE;
CREATE UNIQUE INDEX UX_DimResource_CurrentBK ON dwh.DimResource(ResourceBK) WHERE IsCurrent = TRUE;
CREATE UNIQUE INDEX UX_DimCustomer_CurrentBK ON dwh.DimCustomer(CustomerBK) WHERE IsCurrent = TRUE;
CREATE UNIQUE INDEX UX_DimSupplier_CurrentBK ON dwh.DimSupplier(SupplierBK) WHERE IsCurrent = TRUE;
CREATE UNIQUE INDEX UX_DimProduct_CurrentBK ON dwh.DimProduct(ProductBK) WHERE IsCurrent = TRUE;

/* Helpful lookup indexes */
CREATE INDEX IX_DimProject_BK_Dates ON dwh.DimProject(ProjectBK, SCDStartDate, SCDEndDate);
CREATE INDEX IX_DimWBS_BK_Dates ON dwh.DimWBS(WBSBK, SCDStartDate, SCDEndDate);
CREATE INDEX IX_DimResource_BK_Dates ON dwh.DimResource(ResourceBK, SCDStartDate, SCDEndDate);
CREATE INDEX IX_DimCustomer_BK_Dates ON dwh.DimCustomer(CustomerBK, SCDStartDate, SCDEndDate);
CREATE INDEX IX_DimSupplier_BK_Dates ON dwh.DimSupplier(SupplierBK, SCDStartDate, SCDEndDate);
CREATE INDEX IX_DimProduct_BK_Dates ON dwh.DimProduct(ProductBK, SCDStartDate, SCDEndDate);

/* =========================
   FACTS (DECLARED GRAIN)
   ========================= */

/*
  Grain: one row per Project, WBS, Date, Resource, Customer, Supplier, Product,
  and source document line for planned values.
*/
CREATE TABLE dwh.FactPlanned (
    FactPlannedKey          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ProjectKey              INTEGER NOT NULL,
    WBSKey                  INTEGER NOT NULL,
    DateKey                 INTEGER NOT NULL,
    ResourceKey             INTEGER NOT NULL,
    CustomerKey             INTEGER NOT NULL,
    SupplierKey             INTEGER NOT NULL,
    ProductKey              INTEGER NOT NULL,
    AuditKey                INTEGER NOT NULL,
    DocumentNumber          VARCHAR(80) NULL,
    DocumentLineNumber      INTEGER NULL,
    Quantity                NUMERIC(18,4) NOT NULL DEFAULT 0,
    PlannedHours            NUMERIC(18,2) NOT NULL DEFAULT 0,
    PlannedCost             NUMERIC(18,2) NOT NULL DEFAULT 0,
    PlannedRevenue          NUMERIC(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT PK_FactPlanned PRIMARY KEY (FactPlannedKey),
    CONSTRAINT FK_FactPlanned_Project FOREIGN KEY (ProjectKey) REFERENCES dwh.DimProject(ProjectKey),
    CONSTRAINT FK_FactPlanned_WBS FOREIGN KEY (WBSKey) REFERENCES dwh.DimWBS(WBSKey),
    CONSTRAINT FK_FactPlanned_Date FOREIGN KEY (DateKey) REFERENCES dwh.DimDate(DateKey),
    CONSTRAINT FK_FactPlanned_Resource FOREIGN KEY (ResourceKey) REFERENCES dwh.DimResource(ResourceKey),
    CONSTRAINT FK_FactPlanned_Customer FOREIGN KEY (CustomerKey) REFERENCES dwh.DimCustomer(CustomerKey),
    CONSTRAINT FK_FactPlanned_Supplier FOREIGN KEY (SupplierKey) REFERENCES dwh.DimSupplier(SupplierKey),
    CONSTRAINT FK_FactPlanned_Product FOREIGN KEY (ProductKey) REFERENCES dwh.DimProduct(ProductKey),
    CONSTRAINT FK_FactPlanned_Audit FOREIGN KEY (AuditKey) REFERENCES dwh.DimAudit(AuditKey)
);

/*
  Grain: one row per Project, WBS, Date, Resource, Customer, Supplier, Product,
  and source document line for actual values.
*/
CREATE TABLE dwh.FactActual (
    FactActualKey           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ProjectKey              INTEGER NOT NULL,
    WBSKey                  INTEGER NOT NULL,
    DateKey                 INTEGER NOT NULL,
    ResourceKey             INTEGER NOT NULL,
    CustomerKey             INTEGER NOT NULL,
    SupplierKey             INTEGER NOT NULL,
    ProductKey              INTEGER NOT NULL,
    AuditKey                INTEGER NOT NULL,
    DocumentNumber          VARCHAR(80) NULL,
    DocumentLineNumber      INTEGER NULL,
    Quantity                NUMERIC(18,4) NOT NULL DEFAULT 0,
    ActualHours             NUMERIC(18,2) NOT NULL DEFAULT 0,
    ActualCost              NUMERIC(18,2) NOT NULL DEFAULT 0,
    ActualRevenue           NUMERIC(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT PK_FactActual PRIMARY KEY (FactActualKey),
    CONSTRAINT FK_FactActual_Project FOREIGN KEY (ProjectKey) REFERENCES dwh.DimProject(ProjectKey),
    CONSTRAINT FK_FactActual_WBS FOREIGN KEY (WBSKey) REFERENCES dwh.DimWBS(WBSKey),
    CONSTRAINT FK_FactActual_Date FOREIGN KEY (DateKey) REFERENCES dwh.DimDate(DateKey),
    CONSTRAINT FK_FactActual_Resource FOREIGN KEY (ResourceKey) REFERENCES dwh.DimResource(ResourceKey),
    CONSTRAINT FK_FactActual_Customer FOREIGN KEY (CustomerKey) REFERENCES dwh.DimCustomer(CustomerKey),
    CONSTRAINT FK_FactActual_Supplier FOREIGN KEY (SupplierKey) REFERENCES dwh.DimSupplier(SupplierKey),
    CONSTRAINT FK_FactActual_Product FOREIGN KEY (ProductKey) REFERENCES dwh.DimProduct(ProductKey),
    CONSTRAINT FK_FactActual_Audit FOREIGN KEY (AuditKey) REFERENCES dwh.DimAudit(AuditKey)
);

/*
  Grain: one row per Project, WBS, Date, Resource, Customer, Supplier, Product,
  and source document line for committed values.
*/
CREATE TABLE dwh.FactCommitted (
    FactCommittedKey        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ProjectKey              INTEGER NOT NULL,
    WBSKey                  INTEGER NOT NULL,
    DateKey                 INTEGER NOT NULL,
    ResourceKey             INTEGER NOT NULL,
    CustomerKey             INTEGER NOT NULL,
    SupplierKey             INTEGER NOT NULL,
    ProductKey              INTEGER NOT NULL,
    AuditKey                INTEGER NOT NULL,
    DocumentNumber          VARCHAR(80) NULL,
    DocumentLineNumber      INTEGER NULL,
    Quantity                NUMERIC(18,4) NOT NULL DEFAULT 0,
    CommittedHours          NUMERIC(18,2) NOT NULL DEFAULT 0,
    CommittedCost           NUMERIC(18,2) NOT NULL DEFAULT 0,
    CommittedRevenue        NUMERIC(18,2) NOT NULL DEFAULT 0,
    CONSTRAINT PK_FactCommitted PRIMARY KEY (FactCommittedKey),
    CONSTRAINT FK_FactCommitted_Project FOREIGN KEY (ProjectKey) REFERENCES dwh.DimProject(ProjectKey),
    CONSTRAINT FK_FactCommitted_WBS FOREIGN KEY (WBSKey) REFERENCES dwh.DimWBS(WBSKey),
    CONSTRAINT FK_FactCommitted_Date FOREIGN KEY (DateKey) REFERENCES dwh.DimDate(DateKey),
    CONSTRAINT FK_FactCommitted_Resource FOREIGN KEY (ResourceKey) REFERENCES dwh.DimResource(ResourceKey),
    CONSTRAINT FK_FactCommitted_Customer FOREIGN KEY (CustomerKey) REFERENCES dwh.DimCustomer(CustomerKey),
    CONSTRAINT FK_FactCommitted_Supplier FOREIGN KEY (SupplierKey) REFERENCES dwh.DimSupplier(SupplierKey),
    CONSTRAINT FK_FactCommitted_Product FOREIGN KEY (ProductKey) REFERENCES dwh.DimProduct(ProductKey),
    CONSTRAINT FK_FactCommitted_Audit FOREIGN KEY (AuditKey) REFERENCES dwh.DimAudit(AuditKey)
);

/* Fact table performance indexes (Postgres has no columnstore index type; use btree join-key
   indexes plus a BRIN index on DateKey, which is cheap and effective for large, date-ordered facts) */
CREATE INDEX IX_FactPlanned_JoinKeys ON dwh.FactPlanned(ProjectKey, WBSKey, DateKey, ResourceKey, CustomerKey, SupplierKey, ProductKey);
CREATE INDEX IX_FactActual_JoinKeys ON dwh.FactActual(ProjectKey, WBSKey, DateKey, ResourceKey, CustomerKey, SupplierKey, ProductKey);
CREATE INDEX IX_FactCommitted_JoinKeys ON dwh.FactCommitted(ProjectKey, WBSKey, DateKey, ResourceKey, CustomerKey, SupplierKey, ProductKey);

CREATE INDEX IX_FactPlanned_DateKey_BRIN ON dwh.FactPlanned USING BRIN (DateKey);
CREATE INDEX IX_FactActual_DateKey_BRIN ON dwh.FactActual USING BRIN (DateKey);
CREATE INDEX IX_FactCommitted_DateKey_BRIN ON dwh.FactCommitted USING BRIN (DateKey);

/* =========================
   UNKNOWN MEMBERS (-1)
   ========================= */

INSERT INTO dwh.DimProject (ProjectKey, ProjectBK, ProjectName, ProjectType, ProjectStatus, PlannedStartDate, PlannedEndDate, SCDStartDate, SCDEndDate, IsCurrent, RecordSource)
VALUES (-1, 'UNK', 'Unknown Project', 'Unknown', 'Unknown', NULL, NULL, '1900-01-01', '9999-12-31', TRUE, 'System');

INSERT INTO dwh.DimWBS (WBSKey, WBSBK, WBSName, WBSType, ParentWBSBK, WBSLevel, SCDStartDate, SCDEndDate, IsCurrent, RecordSource)
VALUES (-1, 'UNK', 'Unknown WBS', 'Unknown', NULL, NULL, '1900-01-01', '9999-12-31', TRUE, 'System');

INSERT INTO dwh.DimResource (ResourceKey, ResourceBK, ResourceName, ResourceType, Department, UnitOfMeasure, HourlyRate, SCDStartDate, SCDEndDate, IsCurrent, RecordSource)
VALUES (-1, 'UNK', 'Unknown Resource', 'Unknown', NULL, NULL, NULL, '1900-01-01', '9999-12-31', TRUE, 'System');

INSERT INTO dwh.DimCustomer (CustomerKey, CustomerBK, CustomerName, CustomerSegment, Country, Region, City, SCDStartDate, SCDEndDate, IsCurrent, RecordSource)
VALUES (-1, 'UNK', 'Unknown Customer', 'Unknown', NULL, NULL, NULL, '1900-01-01', '9999-12-31', TRUE, 'System');

INSERT INTO dwh.DimSupplier (SupplierKey, SupplierBK, SupplierName, SupplierCategory, Country, Region, City, SCDStartDate, SCDEndDate, IsCurrent, RecordSource)
VALUES (-1, 'UNK', 'Unknown Supplier', 'Unknown', NULL, NULL, NULL, '1900-01-01', '9999-12-31', TRUE, 'System');

INSERT INTO dwh.DimProduct (ProductKey, ProductBK, ProductName, ProductCategory, UnitOfMeasure, StandardCost, SCDStartDate, SCDEndDate, IsCurrent, RecordSource)
VALUES (-1, 'UNK', 'Unknown Product', 'Unknown', NULL, NULL, '1900-01-01', '9999-12-31', TRUE, 'System');

/* Default unknown date */
INSERT INTO dwh.DimDate (
    DateKey, FullDate, DayNumberOfMonth, DayName, DayOfWeekISO, WeekOfYearISO,
    MonthNumber, MonthName, QuarterNumber, YearNumber, YearMonth, IsWeekend, IsMonthEnd
)
VALUES (
    -1, '1900-01-01', 1, 'Unknown', 1, 1,
    1, 'Unknown', 1, 1900, '1900-01', FALSE, FALSE
);

/* Default unknown audit */
INSERT INTO dwh.DimAudit (AuditKey, BatchId, SourceSystem, LoadStartDtm, LoadEndDtm, LoadStatus, RowsRead, RowsInserted, RowsUpdated, ErrorMessage)
VALUES (-1, 'UNK', 'System', (now() AT TIME ZONE 'utc'), (now() AT TIME ZONE 'utc'), 'Unknown', NULL, NULL, NULL, NULL);

/* Keep the identity sequences ahead of the manually inserted -1 unknown-member keys */
SELECT setval(pg_get_serial_sequence('dwh.DimProject', 'projectkey'), 1, false);
SELECT setval(pg_get_serial_sequence('dwh.DimWBS', 'wbskey'), 1, false);
SELECT setval(pg_get_serial_sequence('dwh.DimResource', 'resourcekey'), 1, false);
SELECT setval(pg_get_serial_sequence('dwh.DimCustomer', 'customerkey'), 1, false);
SELECT setval(pg_get_serial_sequence('dwh.DimSupplier', 'supplierkey'), 1, false);
SELECT setval(pg_get_serial_sequence('dwh.DimProduct', 'productkey'), 1, false);
SELECT setval(pg_get_serial_sequence('dwh.DimAudit', 'auditkey'), 1, false);

/* =========================
   DATE DIMENSION POPULATION
   ========================= */

CREATE PROCEDURE dwh.usp_PopulateDimDate(
    p_start_date DATE,
    p_end_date   DATE
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF p_start_date IS NULL OR p_end_date IS NULL OR p_end_date < p_start_date THEN
        RAISE EXCEPTION 'Invalid date range for DimDate population.';
    END IF;

    WITH RECURSIVE d AS (
        SELECT p_start_date AS FullDate
        UNION ALL
        SELECT (FullDate + INTERVAL '1 day')::date
        FROM d
        WHERE FullDate < p_end_date
    )
    INSERT INTO dwh.DimDate (
        DateKey,
        FullDate,
        DayNumberOfMonth,
        DayName,
        DayOfWeekISO,
        WeekOfYearISO,
        MonthNumber,
        MonthName,
        QuarterNumber,
        YearNumber,
        YearMonth,
        IsWeekend,
        IsMonthEnd
    )
    SELECT
        to_char(d.FullDate, 'YYYYMMDD')::INTEGER AS DateKey,
        d.FullDate,
        EXTRACT(DAY FROM d.FullDate)::SMALLINT AS DayNumberOfMonth,
        TRIM(to_char(d.FullDate, 'Day')) AS DayName,
        EXTRACT(ISODOW FROM d.FullDate)::SMALLINT AS DayOfWeekISO,
        EXTRACT(WEEK FROM d.FullDate)::SMALLINT AS WeekOfYearISO,
        EXTRACT(MONTH FROM d.FullDate)::SMALLINT AS MonthNumber,
        TRIM(to_char(d.FullDate, 'Month')) AS MonthName,
        EXTRACT(QUARTER FROM d.FullDate)::SMALLINT AS QuarterNumber,
        EXTRACT(YEAR FROM d.FullDate)::SMALLINT AS YearNumber,
        to_char(d.FullDate, 'YYYY-MM') AS YearMonth,
        (EXTRACT(ISODOW FROM d.FullDate) IN (6, 7)) AS IsWeekend,
        (d.FullDate = (date_trunc('month', d.FullDate) + INTERVAL '1 month' - INTERVAL '1 day')::date) AS IsMonthEnd
    FROM d
    WHERE NOT EXISTS (
        SELECT 1
        FROM dwh.DimDate x
        WHERE x.FullDate = d.FullDate
    );
END;
$$;

COMMIT;

/* Example:
   CALL dwh.usp_PopulateDimDate('2020-01-01', '2030-12-31');
*/
